# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class MainStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBothNumbers = channel.unary_unary(
                '/Main/AddBothNumbers',
                request_serializer=service__pb2.addMsg.SerializeToString,
                response_deserializer=service__pb2.addReply.FromString,
                )
        self.GetRawDimensons = channel.unary_unary(
                '/Main/GetRawDimensons',
                request_serializer=service__pb2.rawImageMsg.SerializeToString,
                response_deserializer=service__pb2.imageReply.FromString,
                )
        self.GetDotProduct = channel.unary_unary(
                '/Main/GetDotProduct',
                request_serializer=service__pb2.dotProductMsg.SerializeToString,
                response_deserializer=service__pb2.dotProductReply.FromString,
                )
        self.GetJsonDimensons = channel.unary_unary(
                '/Main/GetJsonDimensons',
                request_serializer=service__pb2.jsonImageMsg.SerializeToString,
                response_deserializer=service__pb2.imageReply.FromString,
                )


class MainServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddBothNumbers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRawDimensons(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDotProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJsonDimensons(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBothNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBothNumbers,
                    request_deserializer=service__pb2.addMsg.FromString,
                    response_serializer=service__pb2.addReply.SerializeToString,
            ),
            'GetRawDimensons': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRawDimensons,
                    request_deserializer=service__pb2.rawImageMsg.FromString,
                    response_serializer=service__pb2.imageReply.SerializeToString,
            ),
            'GetDotProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDotProduct,
                    request_deserializer=service__pb2.dotProductMsg.FromString,
                    response_serializer=service__pb2.dotProductReply.SerializeToString,
            ),
            'GetJsonDimensons': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJsonDimensons,
                    request_deserializer=service__pb2.jsonImageMsg.FromString,
                    response_serializer=service__pb2.imageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Main', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Main(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddBothNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Main/AddBothNumbers',
            service__pb2.addMsg.SerializeToString,
            service__pb2.addReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRawDimensons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Main/GetRawDimensons',
            service__pb2.rawImageMsg.SerializeToString,
            service__pb2.imageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDotProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Main/GetDotProduct',
            service__pb2.dotProductMsg.SerializeToString,
            service__pb2.dotProductReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJsonDimensons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Main/GetJsonDimensons',
            service__pb2.jsonImageMsg.SerializeToString,
            service__pb2.imageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
